baseURL: https://darktable-org.github.io/luadocs/
languageCode: en-us
title: darktable Lua documentation
theme:
  - hugo-darktable-docs-theme
markup:
  highlight:
    style: algol_nu
outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  mounts:
    - source: ./themes//hugo-darktable-docs-theme/assets/node_modules/fork-awesome/fonts
      target: static/fonts

